### ISSUE TITLE
Is blinkInput the solution for OCR or is it blinkId?

### ISSUE THREAD

**Issue by one-geek** [blinkinput/blinkinput-cordova#1]
Hi,
I dont really understand the difference between the blinkId and blinkInput.

Until now, i only try the blinkId Solutions on https://github.com/BlinkID/blinkid-phonegap
```
var types = ["PDF417", "UKDL"]; // for barcode driver licences
```

Do you have a sample for blinkinput-phonegap if it the one for OCR.
I mean, i need the Javascript SDK demo. 
I already create my trial license for blinkOCR. But, i dont really know what to do next to activate the OCR.

And this Github is seems to be empty.

**Comment by DoDoENT** [comment]
We still haven't published BlinkInput for Phonegap. However, there are native SDKs ([android](https://github.com/BlinkInput/blinkinput-android) and [ios](https://github.com/BlinkInput/blinkinput-ios)).

Basically, BlinkInput is scraped-down version of BlinkID. It does not support scanning ID documents and passports - it supports only pure barcode recognition and segment scan.

**Comment by one-geek** [comment]
When do you think the phonegap OCR plugin source code will be available.

**Comment by DoDoENT** [comment]
We currently have no roadmap of when phonegap version of BlinkInput will be available. All features available in BlinkInput are also available in BlinkID phonegap version (and much more).
